set_property PACKAGE_PIN E3 [get_ports clk]
set_property PACKAGE_PIN C2 [get_ports rst_n]
set_property PACKAGE_PIN H5  [get_ports led[0]]
set_property PACKAGE_PIN J5  [get_ports led[1]]
set_property PACKAGE_PIN T9  [get_ports led[2]]
set_property PACKAGE_PIN T10 [get_ports led[3]]
set_property PACKAGE_PIN A8  [get_ports switch[0]]
set_property PACKAGE_PIN C11 [get_ports switch[1]]
set_property PACKAGE_PIN C10 [get_ports switch[2]]
set_property PACKAGE_PIN A10 [get_ports switch[3]]
set_property PACKAGE_PIN D9  [get_ports key[0]]
set_property PACKAGE_PIN C9  [get_ports key[1]]
set_property PACKAGE_PIN B9  [get_ports key[2]]
set_property PACKAGE_PIN B8  [get_ports key[3]]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports key[0]]
set_property IOSTANDARD LVCMOS33 [get_ports key[1]]
set_property IOSTANDARD LVCMOS33 [get_ports key[2]]
set_property IOSTANDARD LVCMOS33 [get_ports key[3]]
set_property IOSTANDARD LVCMOS33 [get_ports led[0]]
set_property IOSTANDARD LVCMOS33 [get_ports led[1]]
set_property IOSTANDARD LVCMOS33 [get_ports led[2]]
set_property IOSTANDARD LVCMOS33 [get_ports led[3]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[3]]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property CONFIG_MODE SPIx4 [current_design]
