`define DISPCODE_0    8'hc0
`define DISPCODE_1    8'hf9
`define DISPCODE_2    8'ha4
`define DISPCODE_3    8'hb0
`define DISPCODE_4    8'h99
`define DISPCODE_5    8'h92
`define DISPCODE_6    8'h82
`define DISPCODE_7    8'hf8
`define DISPCODE_8    8'h80
`define DISPCODE_9    8'h90
`define DISPCODE_A    8'h88
`define DISPCODE_b    8'h83
`define DISPCODE_C    8'hc6
`define DISPCODE_d    8'ha1
`define DISPCODE_E    8'h86
`define DISPCODE_F    8'h8e
`define DISPCODE_P    8'h8c
`define DISPCODE_NULL 8'hff
`define DISPCODE_T    8'h87
`define DISPCODE_Y    8'h91
`define DISPCODE_n    8'hab
`define DISPCODE_H    8'h89
`define DISPCODE_h    8'h8b
`define DISPCODE_L    8'hc7
`define DISPCODE_o    8'ha3
`define DISPCODE_LINE_LO 8'hf7
`define DISPCODE_LINE    8'hbf
`define DISPCODE_LINE_UP 8'hfe
`define DISPCODE_u       8'he3
`define DISPCODE_r       8'haf
`define DISPCODE_DOT     8'h7f
`define DISPCODE_ALL     8'h00
`define DISPCODE_J       8'he0
`define DISPCODE_K       8'h0D
`define DISPCODE_U       8'hc1
